services:
  mysql:
    image: mysql:8.4
    container_name: vapor17-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vapor17-app
    # Carga explícitamente el archivo de variables antes de procesar el entorno
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_DOCKER}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: ${JWT_SECRET}
      STEAM_API_URL: ${STEAM_API_URL}
      STEAM_API_KEY: ${STEAM_API_KEY}
    ports:
      - "${APP_HOST_PORT}:8080"
    restart: unless-stopped

volumes:
  mysql_data:
      # Para montar en cualquier lado este docker si o si se tendra que sacar una key de la api de steam asi q no lo podra hacer profe
      # amenos que se cree una porque si no creo que no permite hacer ningun metodo que requiera conexion a la api