spring.application.name=Vapor
server.port=${PORT:8080}

# Conexion a MySQL (valores sensibles por variables de entorno)
spring.datasource.url=${DB_URL_DOCKER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

steam.api-key=${STEAM_API_KEY}
steam.api-url=${STEAM_API_URL}

jwt.secret=${JWT_SECRET}